# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '*/20 * * * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    strategy:
      matrix:
        node-version: ['18.17.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - run: pwd
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'server/package-lock.json'
    
    - run: pwd
    
    - name: npm ci
      run: npm ci
      working-directory: ${{ env.working-directory }}
      
    - run: pwd

    - name: npm start
      run: npm start
      working-directory: ${{ env.working-directory }}

    - run: pwd
